### ISSUE TITLE
Responding with non string in Routes return response - crashes output schema validation

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#61]
Just do this for the script after input schema validation:

```scala
payload = req.attribute("_body") // this should already have the parsed data
```
Error happens:

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "content" is null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1217)
	at cowj.TypeSystem.lambda$outputSchemaVerificationFilter$6(TypeSystem.java:344)
	at spark.FilterImpl$1.handle(FilterImpl.java:73)
	at spark.http.matching.AfterAfterFilters.execute(AfterAfterFilters.java:55)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:187)
```

**Comment by ashis0013** [comment]
Not crashing anymore, we can close this.
